//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGuid
    {
        public TblGuid()
        {
            this.TblLocation = new HashSet<TblLocation>();
        }
    
        public int GuidId { get; set; }
        public string GuidName { get; set; }
        public string GuidSurname { get; set; }
    
        public virtual ICollection<TblLocation> TblLocation { get; set; }
    }
}
