//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFinancalCrmProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinancalCrmDbEntities : DbContext
    {
        public FinancalCrmDbEntities()
            : base("name=FinancalCrmDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BankProcesses> BankProcesses { get; set; }
        public DbSet<Banks> Banks { get; set; }
        public DbSet<Bills> Bills { get; set; }
        public DbSet<Categories> Categories { get; set; }
        public DbSet<Spendings> Spendings { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
