//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.EfProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EfTravelDbEntities1 : DbContext
    {
        public EfTravelDbEntities1()
            : base("name=EfTravelDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TblCustomer> TblCustomer { get; set; }
        public DbSet<TblGuid> TblGuid { get; set; }
        public DbSet<TblLocation> TblLocation { get; set; }
    }
}
