//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.EfProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLocation
    {
        public int LocationId { get; set; }
        public string LocationCity { get; set; }
        public string LocationCountry { get; set; }
        public Nullable<byte> LocationCapacity { get; set; }
        public Nullable<decimal> LocationPrice { get; set; }
        public string DayNight { get; set; }
        public Nullable<int> GuidId { get; set; }
    
        public virtual TblGuid TblGuid { get; set; }
    }
}
